// app/components/Accessibility.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

/**
 * Accessibility Component
 * 
 * Provides comprehensive accessibility features:
 * - Screen reader optimization
 * - Keyboard navigation
 * - Focus management
 * - ARIA labels and roles
 * - Skip to content links
 * - High contrast mode support
 * 
 * @component
 * @returns {JSX.Element} Accessibility wrapper
 */
interface AccessibilityProps {
  children: React.ReactNode;
  skipToContent?: boolean;
  highContrast?: boolean;
  reducedMotion?: boolean;
  className?: string;
}

const Accessibility = ({ 
  children, 
  skipToContent = true,
  highContrast = false,
  reducedMotion = false,
  className = ""
}: AccessibilityProps) => {
  const [isHighContrast, setIsHighContrast] = useState(highContrast);
  const [isReducedMotion, setIsReducedMotion] = useState(reducedMotion);
  const [focusVisible, setFocusVisible] = useState(false);
  const mainContentRef = useRef<HTMLDivElement>(null);

  // Detect user's motion preference
  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
    setIsReducedMotion(mediaQuery.matches);

    const handleChange = () => setIsReducedMotion(mediaQuery.matches);
    mediaQuery.addEventListener('change', handleChange);
    return () => mediaQuery.removeEventListener('change', handleChange);
  }, []);

  // Detect user's contrast preference
  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-contrast: high)');
    setIsHighContrast(mediaQuery.matches);

    const handleChange = () => setIsHighContrast(mediaQuery.matches);
    mediaQuery.addEventListener('change', handleChange);
    return () => mediaQuery.removeEventListener('change', handleChange);
  }, []);

  // Focus management
  useEffect(() => {
    const handleFocusIn = () => setFocusVisible(true);
    const handleFocusOut = () => setFocusVisible(false);

    document.addEventListener('focusin', handleFocusIn);
    document.addEventListener('focusout', handleFocusOut);

    return () => {
      document.removeEventListener('focusin', handleFocusIn);
      document.removeEventListener('focusout', handleFocusOut);
    };
  }, []);

  // Skip to content functionality
  const handleSkipToContent = () => {
    if (mainContentRef.current) {
      mainContentRef.current.focus();
      mainContentRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  };

  // Keyboard navigation helpers
  const handleKeyDown = (e: React.KeyboardEvent) => {
    // Escape key to close modals/menus
    if (e.key === 'Escape') {
      const activeElement = document.activeElement as HTMLElement;
      if (activeElement && activeElement.blur) {
        activeElement.blur();
      }
    }

    // Enter/Space for button activation
    if (e.key === 'Enter' || e.key === ' ') {
      const target = e.target as HTMLElement;
      if (target.tagName === 'BUTTON' || target.getAttribute('role') === 'button') {
        e.preventDefault();
        target.click();
      }
    }
  };

  return (
    <div 
      className={`accessibility-wrapper ${className}`}
      onKeyDown={handleKeyDown}
      style={{
        '--high-contrast': isHighContrast ? '1' : '0',
        '--reduced-motion': isReducedMotion ? '1' : '0',
      } as React.CSSProperties}
    >
            {/* Skip to content link - positioned off-screen by default */}
      {skipToContent && (
        <a
          href="#main-content"
          className="skip-to-content"
          onClick={handleSkipToContent}
        >
          Skip to content
        </a>
      )}

      {/* Main content with accessibility attributes */}
      <main
        ref={mainContentRef}
        id="main-content"
        tabIndex={-1}
        role="main"
        aria-label="Main content"
        className={`main-content ${isHighContrast ? 'high-contrast' : ''} ${isReducedMotion ? 'reduced-motion' : ''}`}
      >
        {children}
      </main>

      {/* Accessibility announcement region */}
      <div
        id="announcements"
        aria-live="polite"
        aria-atomic="true"
        className="sr-only"
        style={{
          position: 'absolute',
          left: '-10000px',
          width: '1px',
          height: '1px',
          overflow: 'hidden',
        }}
      />

      {/* Focus indicator styles */}
      <style jsx>{`
        .accessibility-wrapper {
          --focus-ring: ${isHighContrast ? '3px solid #ffff00' : '2px solid var(--primary)'};
          --focus-ring-offset: ${isHighContrast ? '2px' : '1px'};
        }

        .main-content:focus {
          outline: var(--focus-ring);
          outline-offset: var(--focus-ring-offset);
        }

        .high-contrast {
          --text-color: #ffffff;
          --background-color: #000000;
          --border-color: #ffffff;
          --link-color: #ffff00;
        }

        .reduced-motion * {
          animation-duration: 0.01ms !important;
          animation-iteration-count: 1 !important;
          transition-duration: 0.01ms !important;
        }

        .skip-to-content {
          position: absolute;
          top: -40px;
          left: 6px;
          background: var(--primary);
          color: white;
          padding: 8px 16px;
          text-decoration: none;
          border-radius: 4px;
          font-size: 14px;
          font-weight: 500;
          z-index: 10000;
          transition: top 0.3s ease;
        }

        .skip-to-content:focus {
          top: 6px;
          outline: var(--focus-ring);
          outline-offset: var(--focus-ring-offset);
        }

        /* Screen reader only class */
        .sr-only {
          position: absolute;
          width: 1px;
          height: 1px;
          padding: 0;
          margin: -1px;
          overflow: hidden;
          clip: rect(0, 0, 0, 0);
          white-space: nowrap;
          border: 0;
        }
      `}</style>
    </div>
  );
};

export default Accessibility;

// src/lib/components/Accessibility.svelte
<script lang="ts">
    import { onMount } from "svelte";

    export let skipToContent = true;
    export let highContrast = false;
    export let reducedMotion = false;
    let className = "";
    export { className as class };

    let isHighContrast = highContrast;
    let isReducedMotion = reducedMotion;
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    let focusVisible = false;
    let mainContentRef: HTMLElement;

    onMount(() => {
        // Reduced Motion Preference
        const motionQuery = window.matchMedia(
            "(prefers-reduced-motion: reduce)",
        );
        isReducedMotion = motionQuery.matches;

        const handleMotionChange = (e: MediaQueryListEvent) => {
            isReducedMotion = e.matches;
        };
        motionQuery.addEventListener("change", handleMotionChange);

        // High Contrast Preference
        const contrastQuery = window.matchMedia("(prefers-contrast: high)");
        isHighContrast = contrastQuery.matches;

        const handleContrastChange = (e: MediaQueryListEvent) => {
            isHighContrast = e.matches;
        };
        contrastQuery.addEventListener("change", handleContrastChange);

        // Focus Visibility
        const handleFocusIn = () => (focusVisible = true);
        const handleFocusOut = () => (focusVisible = false);
        document.addEventListener("focusin", handleFocusIn);
        document.addEventListener("focusout", handleFocusOut);

        return () => {
            motionQuery.removeEventListener("change", handleMotionChange);
            contrastQuery.removeEventListener("change", handleContrastChange);
            document.removeEventListener("focusin", handleFocusIn);
            document.removeEventListener("focusout", handleFocusOut);
        };
    });

    function handleSkipToContent(e: MouseEvent) {
        e.preventDefault();
        if (mainContentRef) {
            mainContentRef.focus();
            mainContentRef.scrollIntoView({ behavior: "smooth" });
        }
    }

    function handleKeyDown(e: KeyboardEvent) {
        if (e.key === "Escape") {
            const activeElement = document.activeElement as HTMLElement;
            if (activeElement && activeElement.blur) {
                activeElement.blur();
            }
        }

        if (e.key === "Enter" || e.key === " ") {
            const target = e.target as HTMLElement;
            if (
                (target.tagName === "BUTTON" &&
                    target.getAttribute("type") !== "submit") ||
                target.getAttribute("role") === "button"
            ) {
                // Only prevent default if it's acting as a generic button, standard buttons might need default behavior
                // But the original React code did preventDefault unconditionally for button/role=button
                e.preventDefault();
                target.click();
            }
        }
    }
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
    class={`accessibility-wrapper ${className}`}
    on:keydown={handleKeyDown}
    style:--high-contrast={isHighContrast ? "1" : "0"}
    style:--reduced-motion={isReducedMotion ? "1" : "0"}
>
    {#if skipToContent}
        <a
            href="#main-content"
            class="skip-to-content"
            on:click={handleSkipToContent}
        >
            Skip to content
        </a>
    {/if}

    <main
        bind:this={mainContentRef}
        id="main-content"
        tabindex="-1"
        aria-label="Main content"
        class={`main-content ${isHighContrast ? "high-contrast" : ""} ${isReducedMotion ? "reduced-motion" : ""}`}
    >
        <slot />
    </main>

    <div
        id="announcements"
        aria-live="polite"
        aria-atomic="true"
        class="sr-only"
        style="position: absolute; left: -10000px; width: 1px; height: 1px; overflow: hidden;"
    ></div>
</div>

<style>
    .accessibility-wrapper {
        /* Variables need to be defined or used carefully since CSS variables in style attribute cascade */
        --focus-ring: var(--high-contrast) == 1 ? 3px solid #ffff00: 2px solid
            var(--primary, #3b82f6);
        --focus-ring-offset: var(--high-contrast) == 1 ? 2px: 1px;
    }

    /* Note: CSS variables in property values like above won't work directly with ternary logic in pure CSS withoutcalc/helpers, 
     so we rely on Svelte style attribute for the flags and use CSS custom properties for logic or just class overrides. */

    /* Retaining the original logic via classes is reliable */
    .main-content:focus {
        outline: 2px solid var(--primary, #3b82f6);
        outline-offset: 1px;
    }

    /* High Contrast Mode */
    .high-contrast {
        --text-color: #ffffff;
        --background-color: #000000;
        --border-color: #ffffff;
        --link-color: #ffff00;
    }

    .high-contrast:focus {
        outline: 3px solid #ffff00;
        outline-offset: 2px;
    }

    /* Reduced Motion */
    /* :global(.reduced-motion *) triggers for children */
    :global(.reduced-motion *) {
        animation-duration: 0.01ms !important;
        animation-iteration-count: 1 !important;
        transition-duration: 0.01ms !important;
    }

    /* Skip Link */
    .skip-to-content {
        position: absolute;
        top: -40px;
        left: 6px;
        background: var(--primary, #3b82f6);
        color: white;
        padding: 8px 16px;
        text-decoration: none;
        border-radius: 4px;
        font-size: 14px;
        font-weight: 500;
        z-index: 10000;
        transition: top 0.3s ease;
    }

    .skip-to-content:focus {
        top: 6px;
        outline: 2px solid var(--primary, #3b82f6);
        outline-offset: 1px;
    }

    /* Screen Reader Only */
    .sr-only {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        white-space: nowrap;
        border: 0;
    }
</style>
